### ISSUE TITLE
Handle saturating references with included resource in value[x] fields

### ISSUE THREAD

**Issue by alpchapanolo** [jarimayenburg/fhir-sdk#2]
When a `reference` in a resource is part of a `value[x]` field, the generated code for the `value[x]` takes the shape of an enum that wraps around the different possible types within. An example of this is found in the `DeviceRequest` resource. It has a field `code`, which can either be a `Reference` or a `CodeableConcept` (side-note: the FHIR wiki refers to this as a [CodeableReference](https://build.fhir.org/references.html#CodeableReference)):
```
pub enum DeviceRequestCode {
    /// Variant accepting the Reference type.
    #[serde(rename = "codeReference")]
    Reference(Reference),
    /// Variant accepting the CodeableConcept type.
    #[serde(rename = "codeCodeableConcept")]
    CodeableConcept(CodeableConcept),
}
```

This enum is expected to look a little like: 
```
pub enum DeviceRequestCode {
    /// Variant accepting the Reference type.
    #[serde(rename = "codeReference")]
    Reference(DeviceRequestCodeReference),
    /// Variant accepting the CodeableConcept type.
    #[serde(rename = "codeCodeableConcept")]
    CodeableConcept(CodeableConcept),
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct DeviceRequestCodeReference {
    /// The resource that is being referred to. When doing searches, the client will fill this field if possible.
    #[serde(skip)]
    pub target: Option<Box<Device>>,
    /// The FHIR Reference field
    #[serde(flatten)]
    pub reference: Reference,
}
```

There seem to be two separate issues:
1. Generated code does not differentiate/wrap the reference with a custom reference struct that has a target field.
2. Related to <1>, even if included in the same bundle, the referenced resource is not attached to the reference.

**Comment by adammozes** [comment]
#7 is now merged, and I am closing this in the hope of fixing your issue. :saluting_face:
